/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Reservation = {
  _id: string;
  _type: 'reservation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  phone?: string;
  date?: string;
  people?: number;
  table?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'table';
  };
};

export type Table = {
  _id: string;
  _type: 'table';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  seats?: number;
  price?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  slug?: Slug;
  answer?: string;
};

export type Contact = {
  _id: string;
  _type: 'contact';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  message?: string;
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  duration?: string;
  mainImage?: BlockImage;
  desc?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type BlockImage = {
  _type: 'blockImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  mainImage?: BlockImage;
};

export type Newsletter = {
  _id: string;
  _type: 'newsletter';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
};

export type Menu = {
  _id: string;
  _type: 'menu';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  ingredients?: string;
  mainImage?: BlockImage;
};

export type Review = {
  _id: string;
  _type: 'review';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  mainImage?: BlockImage;
  desc?: string;
  rating?: number;
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  subtitle?: string;
  price?: number;
  discount?: number;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  desc?: BlockContent;
  mainImage?: BlockImage;
  review?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'review';
  }>;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Reservation
  | Table
  | Slug
  | Faq
  | Contact
  | Blog
  | BlockContent
  | BlockImage
  | TeamMember
  | Newsletter
  | Menu
  | Review
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: ALL_TEAM_MEMBERS_QUERY
// Query: *[_type == 'teamMember' && defined(slug.current)]{  name,  slug,  role,  mainImage{    alt,    asset->{url}  } }
export type ALL_TEAM_MEMBERS_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  role: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: ALL_MENU_ITEMS_QUERY
// Query: *[_type == 'menu' && defined(slug.current)]{  name,  slug,  price,  ingredients,  mainImage{    alt,    asset->{url}  } }
export type ALL_MENU_ITEMS_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  price: number | null;
  ingredients: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: ALL_BLOGS_QUERY
// Query: *[_type == 'blog' && defined(slug.current)]|order(publishedAt){  title,  slug,  publishedAt,  mainImage{    alt,    asset->{url}  } }
export type ALL_BLOGS_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: BLOG_QUERY
// Query: *[_type == 'blog' && slug.current == $slug]|order(publishedAt){  title,  slug,  publishedAt,  mainImage{    alt,    asset->{url}  },  desc,  duration }
export type BLOG_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  desc: BlockContent | null;
  duration: string | null;
}>;
// Variable: ALL_FAQS_QUERY
// Query: *[_type == 'faq']{ question,  answer,  slug }
export type ALL_FAQS_QUERYResult = Array<{
  question: string | null;
  answer: string | null;
  slug: Slug | null;
}>;
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == 'product' && defined(slug.current)]{  name,  slug,  price,  discount,  mainImage{    alt,    asset->{url}  } }
export type ALL_PRODUCTS_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: RRODUCT_QUERY
// Query: *[_type == 'product' && slug.current == $slug]{  name,  slug,  price,  discount,  mainImage{    alt,    asset->{url}  },  subtitle,  category,  desc,  review }
export type RRODUCT_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  subtitle: string | null;
  category: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  } | null;
  desc: BlockContent | null;
  review: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'review';
  }> | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    "*[_type == 'teamMember'\n && defined(slug.current)]{\n  name,\n  slug,\n  role,\n  mainImage{\n    alt,\n    asset->{url}\n  }\n }": ALL_TEAM_MEMBERS_QUERYResult;
    "*[_type == 'menu'\n && defined(slug.current)]{\n  name,\n  slug,\n  price,\n  ingredients,\n  mainImage{\n    alt,\n    asset->{url}\n  }\n }": ALL_MENU_ITEMS_QUERYResult;
    "*[_type == 'blog'\n && defined(slug.current)]\n|order(publishedAt){\n  title,\n  slug,\n  publishedAt,\n  mainImage{\n    alt,\n    asset->{url}\n  }\n }": ALL_BLOGS_QUERYResult;
    "*[_type == 'blog'\n && slug.current == $slug]\n|order(publishedAt){\n  title,\n  slug,\n  publishedAt,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  desc,\n  duration\n }": BLOG_QUERYResult;
    "*[_type == 'faq']{\n question,\n  answer,\n  slug\n }": ALL_FAQS_QUERYResult;
    "*[_type == 'product'\n && defined(slug.current)]{\n  name,\n  slug,\n  price,\n  discount,\n  mainImage{\n    alt,\n    asset->{url}\n  }\n }": ALL_PRODUCTS_QUERYResult;
    "*[_type == 'product'\n && slug.current == $slug]{\n  name,\n  slug,\n  price,\n  discount,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  subtitle,\n  category,\n  desc,\n  review\n }": RRODUCT_QUERYResult;
  }
}
